### ISSUE TITLE
2020 Issues

### ISSUE THREAD

**Issue by keeganrowe** [pmatthews05/spfx-IsExternallyShared#1]
Hi there

This doesn't work with the latest Powershell PNP and so I installed the version from February 2018 and have the same result.

I call Apply-PnPProvisioningTemplate and see a popup but no verbose output. When I then call  Get-PnPApp, it is not listed.

The readme.md mentions "you can then add the column to any list manually" however it doesn't say what or how. I've determined that it is a text field but what other settings do I need for it to appear? 

Thank you

**Comment by pmatthews05** [comment]
Hi @keeganrowe,
It has been a long while since I looked at this code.

In the PNP template that is provided, there is a site column that get's created called Externally Shared, you will find it in the group called "SPFX Columns"

ID "1c0fa51d-ba22-4281-a281-bed3938bbb57" 

This field has the ClientSideComponentID which matches the SPFX component. You will need to add this column to your library, either directly or to the content type you are using on the library.

Then after you have shared the document externally, it should (or on a refresh) show you that the document is externally shared.

If you are still having issues, then at the weekend, if I find some time, I will attempt to install on my tenant and see if I can work out the issue.

**Comment by keeganrowe** [comment]
Thanks for your quick reply @pmatthews05 

I've now checked the site columns and it does exist, which is strange given that it doesn't appear in the list of Apps using that earlier command. Following your instructions I've now added it in to the list,  I do not see an icon, although the item is shared with externals (and has the text in the Info panel of "This item has been shared with guests"). I have just now modified the icon code slightly to (temporarily) show a 'not shared' icon when appropriate, yet still no icon appears. I've used Dev Tools to search for code references to see if the JS is even loaded on the page, and it seems that it is not there (e.g. searching for the base64 strong of 'SHARED_ICON').

If you have any hints on how to debug that would be great.

My current plan, given I don't know what the core issue is, was to create a brand new SPFX App, get it working, and then migrate across your code/logic/API calls. However your app is definitely a good base for what I need to achieve.

Thanks

**Comment by pmatthews05** [comment]
Where have you deployed the App to? Site Collection or Tenant Level? Can you see the App in the App Catalog at the correct level?

There are a few log messages that should show up in the devtools console if it has loaded correctly. 

Should be able to debug following the following link.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension#debug-your-application-customizer

**Comment by keeganrowe** [comment]
I've tried a few different deploy locations but the current is https://XXXX.sharepoint.com/sites/SaveItPoC/ExternalAccessTest/Forms/AllItems.aspx

I can't debug following those instructions due to some errors (debugManifestsFile not accessible) but I'll look into that.

Cheers

**Comment by pmatthews05** [comment]
Hi @keeganrowe,
 I have gone through the steps again, on my laptop that has never had the code on before. 

I have updated the readme.md file with better instructions around how to deploy the SPFX. 

You can see from my screenshot below I got it working. 
![Success](https://user-images.githubusercontent.com/6736509/95658841-5dbfc600-0b15-11eb-9dd8-8e954ff45cf5.PNG)

Please confirm the extra steps I've put into the Readme file has help you.

**Comment by pmatthews05** [comment]
I've just updated the code to use SPFX 1.11.0 instead of the 1.4.1 that it originally was.

**Comment by keeganrowe** [comment]
Hi @pmatthews05 

I've downloaded the latest to a new location and when I get up to the step "gulp bundle --ship" I get a webpack error with a file  not existing that is referenced in config.json.

Any thoughts?

`Error - [webpack] 'dist':
Entry module not found: Error: Can't resolve 'D:/temp/spfx-IsExternallyShared-master-2020-v2/lib/extensions/isExternallyShared/IsExternallySharedFieldCustomizer.js' in 'D:/temp/spfx-IsExternallyShared-master-2020-v2'
resolve 'D:/temp/spfx-IsExternallyShared-master-2020-v2/lib/extensions/isExternallyShared/IsExternallySharedFieldCustomizer.js' in 'D:/temp/spfx-IsExternallyShared-master-2020-v2'
  using description file: D:/temp/spfx-IsExternallyShared-master-2020-v2/package.json (relative path: .)`

Thanks

**Comment by pmatthews05** [comment]
@keeganrowe 
Sorry that was my fault after the upgrade I missed a line from the new tsconfig.json file. As I didn't do a clean rebuild (delete node_module folder, SharePoint folder),  the files were already there when I did the gulp --bundle.

Now I've done a clean install again, and (fingers cross) this should allow you to build the application customiser.

**Comment by keeganrowe** [comment]
Thanks for your help so far.

I can build it now and the updated readme.md really helps. I see the share icon.

There's just one last issue - when I'm not running gulp serve I see an error/warning,

`Errror loading debug manifests

Error loading debug script. Ensure the server is running and the "debugManifestsFile" parameter URL is correct.

Error: script error for "https://localhost... "`

Is it stuck in debug mode?
Thoughts?

**Comment by pmatthews05** [comment]
@keeganrowe 
I think that you are debugging it wrong. (Possibly).

You see in the [launch.json](https://github.com/pmatthews05/spfx-IsExternallyShared/blob/master/.vscode/launch.json) file, under Field Customizer Debug, change "https://<tenant>.sharepoint.com/Shared%20Documents/Forms/AllItems.aspx" before the '?' to match your environment. 

The part that says `fieldCustomizers={%22External%22:{%22id%22:%225a2b5791-4f5e-4ae8-a4ef-59287f6f9b09%22` The word External should match the name of your column. 

Type `gulp serve --nobrowser`

Then in visual studio code, click debug, then select Field Customizer Debug in the dropdown, then click the play button.
![image](https://user-images.githubusercontent.com/6736509/95747974-3857c700-0c91-11eb-84bf-1bbe5c856a15.png)

This will load up a browser, sign in, and your break points should then be hit. 

I think previously I sent you the wrong debugging documentation, that was for Application Customizers, where what you are trying to debug is a field customizer. If above is no good, try the below link.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer#debug-your-field-customizer

**Comment by keeganrowe** [comment]
Thanks, I thought I had the latest master but I didn't.

All looks good now, cheers for your help.

**Comment by pmatthews05** [comment]
More than welcome. Nice to know my blogs are used by people, and that they are willing to pull me up on my code.

**Comment by keeganrowe** [comment]
Hi @pmatthews05. Regarding the debug mode.. I've triple checked everything, and no matter what I do the remote site attempts to connect to localhost for the debug scripts. How do I turn this off / disable debugging? This is the latest master with the latest changes. I see the settings in the launch.json etc but I don't want to debug at all, just have it working for now.

Thanks

**Comment by pmatthews05** [comment]
@keeganrowe Debugging is always done against the localhost, which is why on the debugging instructions I said you need to run gulp serve --nobrowser.

You see in the launch.json file, under Field Customizer Debug (line 28) the location of the manifest file is a query parameter.

`loadSPFX=true&debugManifestsFile=https://localhost:4321/temp/manifests.js`

If you don't want to debug, then you just deploy according to the readme file, as this deploys it directly to SharePoint to use. There is no need to run gulp serve after the app is in the appcatalog. Also just go to the site as normal. No additional query parameters that points to the debugManifestFile.

**Comment by keeganrowe** [comment]
I don't want to debug. I have it installed via the App Catalog, yet it is
trying to access the manifest. I gathered that the settings in the config
(the were deployed into the App Catalog) were somehow set to debug mode.

How would I debug it without deploying it to the App Catalog? The other
steps to apply the PNP template?

Thanks

**Comment by pmatthews05** [comment]
I'm not 100% sure I'm following you.

When you are debugging, you are always debugging it from your "localhost" even if it's deployed to the App Catalog. You can only debug from localhost. If you don't want to deploy it to the app catalog, then you would just (according to Microsoft Documentation) 

- Ensure the /config/serve.json is configured correctly, with your PageURL, InternalFieldName, and id matching the SPFX extension ID. (5a2b5791-4f5e-4ae8-a4ef-59287f6f9b09)
- Then run a `gulp build` and a `gulp serve` and it should open the page and allow you to debug

I've tried to make it easier, where I run from VSCode debugger, you just need to configure the launch.json file to point to your library, run `gulp serve --nobrowser` then the play button on the debugger. 

The PNP template is just a way to create a column that is associated with the SPFX Field customizer. 

The code works end to end, it is possible to debug, and deploy. I'm afraid I cannot help you any further. Without meaning to sound rude, I suggest you read MS documentation on SPFX Field Customiser. 
Good luck!
